blank_issues_enabled: true
contact_links:
  - name: Ask a question‚ùì
    url: https://github.com/ahsanjoyia/cleanarchitecture/discussions/new
    about: Ask a question or request support for using the clean architecture template
